apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-stdout
  name: go-stdout
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-stdout
  type: ClusterIP